function q = S(q, c, b, d, v)
th = q(5);
s = [...
        c*(b*cos(th)-d*sin(th)), c*(b*cos(th)+d*sin(th));...
        c*(b*sin(th)+d*cos(th)), c*(b*sin(th)-d*cos(th));...
        c, -c;...
        1, 0;...
        0, 1;...
    ];
dq = s*transp(v);
q = dq;
end
